### ISSUE TITLE
Merge into TinyCsvParser as TinyCsvParser 3.0

### ISSUE THREAD

**Issue by bytefish** [jtmueller/TinyCsvParser#3]
@jtmueller I read your changes to the code with great interest, especially the use of ``Span``, Pipelines and ``IAsyncEnumerable`` in your recent branch. And I think it deserves a much wider audience, because it is a very efficient implementation and there is a lot, lot to learn from your implementation!

I know back then we did a split between TinyCsvParser and CoreCsvParser, because I didn't feel comfortable with dropping .NET Framework support. But now I think your implmentation should be made TinyCsvParser 3.0 to get the audience it deserves and focus TinyCsvParser completely on modern .NET Core.

What do you think? I would be really excited!

Most of this is your work, so I don't want to take credit away from your work. We could see how to best share Repository Ownership and the NuGet Package Management.

**Comment by jtmueller** [comment]
Sorry I missed this message from a week ago! Noticed this
<https://github.com/jtmueller/CoreCsvParser/blob/core_3/CoreCsvParser/CoreCsvParser.Benchmark/BenchmarkResults.txt>,
did you?

I'm okay with re-merging CoreCsvParser back into TinyCsvParser if you're
okay with the breaking API changes. Although, for the IAsyncEnumerable
stuff (which is honestly much easier to work with than the IObservable
version it replaced) we may want to wait until C# 8 is somewhere past the
"preview 1" stage. Now that I solved my bugs with the Pipelines code in the
core_3 branch, I could fix the IObservable code in the "pipelines" branch
to work with .NET Core 2.2 and C# 7.3, if we didn't want to wait for
IAsyncEnumerable to come out of preview.

It may be possible to avoid dropping .NET Framework support in the process.

I've recently been working on this:
https://github.com/jtmueller/Collections.Pooled
It uses System.Buffers.ArrayPool and Span to get some amazing upgrades to
the standard List<T> and it works on both .NET Standard 2.0 (.NET 4.6.1+)
and .NET Core 2.2 (it references the System.Buffers and System.Memory Nuget
packages in the .NET Standard build only).

We might be able to do something similar for the CSV parsing - the biggest
obstacle being lack of framework support for parsing numbers/dates/etc out
of ReadOnlySpan<char>. However, we could in theory provide our own
implementations of this in a conditional-compliation block used for the
.NET Standard build only. It might not be as efficient as the .NET Core
version, but should get the job done with fewer string allocations. I've
got some example code lying around somewhere that already does this for
integers and a few other primitive types, but not everything we would need.

**Comment by bytefish** [comment]
Merry Christmas! 🎅 

Yes, I saw your benchmark results and thought this should get a much, much larger audience. Impressive work!

You are right about the ``IAsyncEnumerable``, we should wait until C# 8 is stable and .NET Core 3 is rolled out. And then release it. So if you have the .NET Core 2.2 code in a way you are comfortable with, we could merge it into TinyCsvParser and iterate on it.

I will look into the Collections.Pooled project and see if I can make contributions. 😎 It would be great to support .NET Framework 4.6.1! 

But if it turns out to be too complicated to support .NET Framework 4.6.1, I would be totally OK to drop the support and go all-in on .NET Core.

There is one thing: I didn't look into the Pipeline Branch Code in detail yet, so maybe the following doesn't apply. I would like to get rid of the ``ParallelQuery`` of TinyCsvParser. The ParallelQuery doesn't provide much of a speedup and is an unnecessary complexity.

**Comment by bytefish** [comment]
@jtmueller I am going ahead and create a TinyCsvParser 3.0 branch, which contains the Pipelines Code. We can later iterate on it and merge it when .NET Core is more stable? I hope it's OK, because at the moment I have several use-cases where TinyCsvParser 2.0 is just too slow.

**Comment by bytefish** [comment]
@jtmueller I have released a 3.0.0-alpha1, which includes the ``ReadOnlySpan`` variant of TinyCsvParser.

Ah too bad, the ``ReadOnlySpan<char>`` based method doesn't give me any significant speedup in my experiments. But the memory consumption is lower. 👍 I will keep on researching, where I can improve the performance. 

But I have a gut feeling... 

In the following issue of a different project I have run a Benchmark with TinyCsvParser 2.0.0:

* https://github.com/dfederm/DelimiterSeparatedTextParser/issues/7

In this benchmark a ``string.Split`` method was just as fast as TinyCsvParser. This means: No matter how much I optimize the hell out of the mappings, when using a ``StringSplitTokenizer`` this will always be the lower bound I am able to achieve:

![image](https://user-images.githubusercontent.com/239373/50729549-2ea84380-113c-11e9-86c3-f87b519d0fcc.png)

What do you think?
